-- TZ_ORGANIZATION_SITE
DROP TABLE IF EXISTS TZ_ORGANIZATION_SITE;
CREATE TABLE TZ_ORGANIZATION_SITE (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `ORGANIZATION_CODE` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '机构编号',
  `NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE COMMENT '站点名称,唯一键',
  `SITE_NAME` varchar(20) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL COMMENT '站点别名,英文字母',
  `SITE_TYPE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '站点类型,A:功能站点B：CMS站点所谓功能站点就是比如教务系统学生端这类的功能性站点，CMS站点，就是门户网站这类的类容展示站点',
  `SITE_DESC` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '站点说明',
  `SITE_ENABLE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '是否启用,Y：启用N：不启用',
  `SITE_PATH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '站点路径',
  `SITE_CSS` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '站点样式,用于配置页面样式',
  `SITE_PHONE_CSS` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '站点手机端样式,用于配置手机页面样式',
  `SITE_ISSUE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '发布状态,Y：发布N：未发布',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='机构站点定义表';


-- TZ_SITE_COLU
DROP TABLE IF EXISTS TZ_SITE_COLU;
CREATE TABLE TZ_SITE_COLU (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `SITE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '所属站点,站点表外键',
  `NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE COMMENT '栏目名称,唯一键',
  `COLU_TYPE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '栏目类型,A：单页B:列表C:跳转D:活动',
  `COLU_ENABLE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '是否启用,Y：启用N：不启用',
  `COLE_PATH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '栏目路径',
  `TEMP_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '站点模板,模板表主键',
  `ART_TYPE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容类型,内容类型表主键',
  `F_COLU_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上级栏目,用于树型栏目',
  `COLU_LEVEL` int(11) NOT NULL COMMENT '栏目级别,用于树型栏目，从0开始',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点栏目表';


-- TZ_SITE_TEMP
DROP TABLE IF EXISTS TZ_SITE_TEMP;
CREATE TABLE TZ_SITE_TEMP (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `SITE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '所属站点,站点表外键',
  `NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE COMMENT '模板名称,唯一键',
  `TEMP_TYPE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模板类型,A：单页B:列表',
  `TEMP_ENABLE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '是否启用,Y：启用N：不启用',
  `TZ_TEMP_PCCODE` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PC模板',
  `TZ_TEMP_MSCODE` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机模板',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点模板';


-- TZ_SITE_ART
DROP TABLE IF EXISTS TZ_SITE_ART;
CREATE TABLE TZ_SITE_ART (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `SITE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '所属站点,站点表外键',
  `ART_TITLE` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE COMMENT '内容标题,唯一键',
  `ART_TITLE_STYLE` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '带样式标题',
  `ART_SHORTTITLE` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '短标题',
  `SUBHEAD` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '副标题',
  `ART_ADD_TYPE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容附加字段类型,内容类型表主键',
  `ART_TYPE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'A' COMMENT '内容类型,A:自建文章B:外部引用',
  `START_DATE` date DEFAULT NULL COMMENT '开始日期,用于活动',
  `START_TIME` time DEFAULT NULL COMMENT '开始时间,用于活动',
  `END_DATE` date DEFAULT NULL COMMENT '开始日期,用于活动',
  `END_TIME` time DEFAULT NULL COMMENT '开始时间,用于活动',
  `ART_CONENT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '具体内容',
  `OUT_ART_URL` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '外部链接URL',
  `METAKEYS` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'METAkey',
  `METADESC` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'META描述',
  `ART_EDITTYPE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'A' COMMENT '编辑模式,A:富文本编辑器B:文本编辑器',
  `ABOUT` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容简介',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点内容表';


-- TZ_SITE_ADD_ART
DROP TABLE IF EXISTS TZ_SITE_ADD_ART;
CREATE TABLE TZ_SITE_ADD_ART (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法和TZ_SITE_ART表一致',
  `TZ_TXT1` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_TXT2` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_TXT3` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_TXT4` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_LONG1` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_LONG2` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_LONG3` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TZ_DATE1` date DEFAULT NULL,
  `TZ_DATE2` date DEFAULT NULL,
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点内容附加内容表';


-- TZ_SITE_ART_IMAGE
DROP TABLE IF EXISTS TZ_SITE_ART_IMAGE;
CREATE TABLE TZ_SITE_ART_IMAGE (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `ART_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容,内容表主键',
  `IMAGE_TYPE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片类型,A:标题图B:图片墙，标题图最多只有一张，图片墙可以有多张',
  `IMAGE_TITLE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标题图标题',
  `IMAGE_DESC` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标题图描述',
  `IMG_TRS_URL` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片跳转URL',
  `IMG_SORT` int(11) DEFAULT NULL COMMENT '图片排序,用于图片墙',
  `FILE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '附件表ID',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='内容图片表';


-- TZ_ART_ADD_TYPE
DROP TABLE IF EXISTS TZ_ART_ADD_TYPE;
CREATE TABLE TZ_ART_ADD_TYPE (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE COMMENT '名称,唯一',
  `TYPE_ENABLE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '是否启用,Y：启用N：不启用',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='内容类型表';


-- TZ_ART_ADD_TYPE_FIELD
DROP TABLE IF EXISTS TZ_ART_ADD_TYPE_FIELD;
CREATE TABLE TZ_ART_ADD_TYPE_FIELD (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `TYPE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容类型,内容类型表外键',
  `FIELD_VALUE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '类型的值,站点内容附加内容表里面附加字段',
  `FIELD_DESC` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '类型的描述',
  `SEQ` int(11) NOT NULL COMMENT '显示的排序',
  `TYPE_ENABLE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y' COMMENT '是否启用,Y：启用N：不启用',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='内容类型字段表';


-- TZ_SITE_ART_FILE
DROP TABLE IF EXISTS TZ_SITE_ART_FILE;
CREATE TABLE TZ_SITE_ART_FILE (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `ART_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容,内容表主键',
  `FILE_SORT` int(11) DEFAULT NULL COMMENT '文件排序',
  `FILE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '附件,附件表主键',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='内容附件表';


-- TZ_COLU_ART
DROP TABLE IF EXISTS TZ_COLU_ART;
CREATE TABLE TZ_COLU_ART (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `SITE_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '所属站点,站点表外键',
  `COLU_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '栏目编号,栏目表外键',
  `ART_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容,内容表外键',
  `ART_PUB_DT` datetime DEFAULT NULL COMMENT '内容最新的发布时间',
  `ART_PUB_STATE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'N' COMMENT '发布状态,Y:已经发布N：未发布',
  `ART_URL` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章动态URL',
  `STATIC_ART_URL` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章静态URL,如果发布成静态的HTML',
  `ART_SEQ` int(11) NOT NULL COMMENT '本栏目文章顺序',
  `MAX_ZD_SEQ` int(11) DEFAULT NULL COMMENT '置顶顺序,每次置顶次序+1',
  `PUBLISHER` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容发布者,用户ID',
  `PUB_DEP` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发布部门,部门ID',
  `ART_HTML` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章HTML代码',
  `ART_PHONE_HTML` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章手机HTML代码',
  `ART_CONENT_SCR` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章发布HTML代码',
  `STATIC_FLAG` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '是否静态化,A:静态化B:不静态化 如果有访问限制，只能是B 如果是A那么才有STATIC_NAME输入框',
  `PROJECT_LIMIT` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'A' COMMENT '访问限制,A:无限制B:指定群组',
  `ART_PHONE_CONENT_SCR` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章发布手机HTML代码',
  `STATIC_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章生成静态文件名自定义',
  `STATIC_AOTO_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章生成静态文件名自动',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='栏目内容关联表';


-- TZ_COLU_ART_GROUP
DROP TABLE IF EXISTS TZ_COLU_ART_GROUP;
CREATE TABLE TZ_COLU_ART_GROUP (
  `ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL PRIMARY KEY COMMENT '主键,雪花算法',
  `COLU_ART_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '栏目内容,栏目内容ID',
  `GROUP_ID` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '群组,群组ID',
  `COMMENTS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `MODIFICATION_NUM` int NOT NULL DEFAULT '0' COMMENT '修改记录号',
  `CREATED_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '创建人',
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPD_BY` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ADMIN0000000000001' COMMENT '更新人',
  `LAST_UPD` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='栏目内容权限表';


